### ISSUE TITLE
register page

### ISSUE THREAD

**Issue by santhitak** [condinoaljoseph/meaningful#34]
Should the site have a register page? 
I would place the button in the login modal and the register modal would pop up after that.

Anyways, I would only create a front-end for that. What information would you want to collect from users?

**Comment by condinoaljoseph** [comment]
Sorry for the late reply. For now, I only need the username and password from the user. I'll be happy if you send a PR. Thanks!

**Comment by santhitak** [comment]
No need to apologize! And sure, I'd love to do that!
